kind: Issuer
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  name: letsencrypt-staging
  namespace: kube-system
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    email: route666@live.cn
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}